Migrate from plural to singular names in namespaces
doganoo/PHPAlgorithms pull request #11
Opened 2019-10-07 07:23 UTC by krlv

## Description
Renamed following namespaces:
- `doganoo\PHPAlgorithms\Datastructure\Lists\{ArrayLists => ArrayList}\ArrayList`
- `doganoo\PHPAlgorithms\Datastructure\Lists\{ArrayLists => ArrayList}\StringBuilder`
- `doganoo\PHPAlgorithms\Datastructure\Lists\{LinkedLists => LinkedList}\DoublyLinkedList`
- `doganoo\PHPAlgorithms\Datastructure\Lists\{LinkedLists => LinkedList}\SinglyLinkedList`
- `doganoo\PHPAlgorithms\Datastructure\{Maps => Map}\HashMap`
- `doganoo\PHPAlgorithms\Datastructure\{Maps => Map}\IntegerVector`
- `doganoo\PHPAlgorithms\Datastructure\{Maps => Map}\Map`
- `doganoo\PHPAlgorithms\Datastructure\{Sets => Set}\HashSet`
- `doganoo\PHPAlgorithms\{Maps => Map}\HashMapTest`
- `doganoo\PHPAlgorithms\{Maps => Map}\NodeTest`
- `doganoo\PHPAlgorithms\{Sets => Set}\HashSetTest`

## Related Issue
#6 

## Motivation and Context
#6 

**NB!** Following namespace left in plural names:
- `doganoo\PHPAlgorithms\Datastructure\Lists`
- `doganoo\PHPAlgorithms\Common\Abstracts`
- `doganoo\PHPAlgorithms\Common\Interfaces`

These namespaces cannot be renamed to singular form, because `list`, `abstract` and `interface` are reserved words in PHP

## How Has This Been Tested?
By running PHPUnit tests
```bash
$ phpunit
PHPUnit 6.5.0 by Sebastian Bergmann and contributors.

.....S...........S............................................... 65 / 94 ( 69%)
.............................                                     94 / 94 (100%)
```

2019-10-07 13:07 UTC, doganoo requested changes
Hey

thank you for this PR.
Could you please add a author tag to each files header that you have changed? 

like this:

> @author Firstname Lastname \<mail [at] example.com\>

Thank you for contributing to PHPAlgorithms 😊

2019-10-07 13:16 UTC, doganoo commented
Hey, 

thank you for this PR.

there is still one little thing to do, please have a look in the PR.

2019-10-08 03:22 UTC, krlv commented
Hey @doganoo ! Thank you for the awesome repo!

Regarding your change request - PHPDoc has dedicated [@copyright tag](https://docs.phpdoc.org/references/phpdoc/tags/copyright.html) for that matter. Do you want me to add it as well?

```php
/**
 * Class Map
 *
 * @package doganoo\PHPAlgorithms\Datastructure\Map
 * @author Dogan Ucar, <dogan@dogan-ucar.de>
 * @copyright 2019 Dogan Ucar
 */
```

Let me know what you think

2019-10-08 08:39 UTC, doganoo commented
Hey @krlv 

my aim is to mention and thank all contributors. Therefore, you it would be great if you add your own name like:

```
/**
 * MIT License
 *
 * Copyright (c) 2018 Dogan Ucar, <dogan@dogan-ucar.de>
 * 
 * @author Eugene Kirillov <eug.krlv@gmail.com>
```

2019-10-08 17:41 UTC, krlv commented
Hey @doganoo! Sorry, I got a wrong idea that you want to add PHPDoc `@author` tags.

> my aim is to mention and thank all contributors
That's very generous of you! I'd be honored to add my name to changed files!

2019-10-09 08:09 UTC, doganoo approved these changes

2019-10-09 08:11 UTC, merged

2019-10-09 08:12 UTC, doganoo commented
@krlv thanks for this PR.

Merging this PR into master, we reached our milestone for 1.0.0, which is going to be released ASAP 🎉